version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    branches:
      only:
        - master
        - circleci-test
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Circle ci test.
      - run:
          name: Print the Current Time
          command: date