version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Circle ci test.
      - run:
          name: Print the Current Time
          command: date
  test:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Test
          command: echo test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test